name: Stage Deployment 
on:
  push:
    branches:
      - main
jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: Stage
    steps:
      - name: Deploy to Stage
        run: echo "Deploy to Stage"