name: Production Deployment 
on:
  push:
    branches:
      - main
jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Deploy to Production
        run: echo "Deploy to Production"